### ISSUE TITLE
Unable to use in browser (Uncaught ReferenceError)

### ISSUE THREAD

**Issue by johnd0e** [Download/ulog#20] opened 2019-08-06 08:44 UTC
The last version that has no problem is 1.1.0 (https://cdn.rawgit.com/download/ulog/1.1.0/ulog.min.js)

With all versions after that (355d8a94ae6f91497caabb261ec76b287a38e295 and up) I get:
```
Uncaught ReferenceError: module is not defined
```

**Comment by Download** [comment] 2019-08-26 07:22
Please stay on 1.1.0 for the time being
I am working on 2.0 but it has some issues as you found

**Comment by johnd0e** [comment] 2019-08-31 20:46
Well, I've already started to use v2..
Are there some really critical issues?

**Comment by Download** [comment] 2019-09-03 20:02
@johnd0e 
Not that I am aware of, no.
But...
It really is a WIP and there will be some breaking changes.

* I am making the API compatible with [anylogger](https://npmjs.com/package/anylogger)
* I am removing the logging methods from the `ulog` function
* I am removing the ability to create unnamed loggers
* I am removing `time`, `timeEnd` etc and other 'dummy' methods that were only there to make `ulog` a polyfill for the console... I don't think that functionality is needed in core anymore in 2019. There will probably be some separate entry point that adds these methods back in for those people that really need it
* I am adding advanced configuration options
* I am removing the option to configure from the URL (?log=debug) because I find that localStorage is much better and does not cause side effects (of a changed URL)

**Comment by johnd0e** [comment] 2019-09-04 06:17
> * I am removing the logging methods from the `ulog` function

Now it's possible to call `ulog.log(...)` directly, but in next update we will need to use `var log = ulog('my'); log.log(...)`
Right?


> * I am removing the ability to create unnamed loggers

I am not aware of what you mean. Was it ever documented?


> * I am removing the option to configure from the URL

Is it necessary to remove this part?
`localStorage` has some advantage, but in some cases URL query is more convenient.
For example:
- It's easier to share URL (especially when asking someone to check work in his environment)
- It's possible to make bookmarks for different logging settings
- It's convenient for some one-time setup - check and forget.
  Using `localStorage` I would also need to reset that setup, otherwise it will persist.
  BTW, consider using `sessionStorage` as well.

**Comment by Download** [comment] 2019-09-04 07:22
> Now it's possible to call ulog.log(...) directly, but in next update we will need to use var log = ulog('my'); log.log(...)
> Right?

Yes, that's right. All new features work for named loggers. Especially the new settings feature I am working on allows you to specify settings for classes of loggers and having this static logger makes that harder.

> I am not aware of what you mean. Was it ever documented?
No I don't think it was documented but you could pass empty string and get a logger with empty string as the name

> Is it necessary to remove this part?
Well... no. I can be convinced otherwise  :)
The reason I was thinking about removing it was that from my experience, changing the URL sometimes has side-effects on the website itself and also the setting gets lost every time you click a link or button. But the points you mention are very valid... I need to think about it some more...

> BTW, consider using sessionStorage as well.
Yeah might be a good idea...
Personally I like it that it persists though... Because in practice I set the logging to the level I like and just keep it there. But maybe `ulog` can simply read from both locations...

Thanks for this great feedback!

**Comment by johnd0e** [comment] 2019-09-04 07:36
> changing the URL sometimes has side-effects on the website itself and also the setting gets lost every time you click a link or button

Yes, it has limitations, and can serve as supplementary way only.
Some thoughts:
- to lower side-effects ulog could rely on #hash-part (instead of ?query=).
- it could restore own url-part on `window.onhashchange` (or other technique)
- it could just be used to import settings to `sessionStorage`.


> But maybe `ulog` can simply read from both locations...

It would be convenient.
Perhaps some timestamp is necessary to find which of locations to use.


> Personally I like it that it persists though...

Sure, it is good too. I like `ulog` for it's flexibility.



> Thanks for this great feedback!

Thank you for great logger)

**Comment by johnd0e** [comment] 2019-09-04 07:48
> Perhaps some timestamp is necessary to find which of locations to use.

For most cases `sessionStorage` should have priority, but we need some simple way to switch back to `localStorage`.
May be we can just empty it in console, or via url query.

BTW, to keep `ulog` tiny, all 'extra' features could come into some sub-module.

**Comment by Download** [comment] 2019-09-08 10:53
I currently came up with this function to read settings from the environment on the browser:

```js
ulog.env = function(n, m){
  var result
  n = name(n)
  result = (m = location.search.match('[?&]'+n+'(=([^&]*))?&?')) && m[2]
  try {result = result || sesssionStorage.getItem(n)} catch(e) {/* ignore */}
  try {result = result || localStorage.getItem(n)} catch(e) {/* ignore */}
  return result
}

This code checks the URL, sessionStorage and localStorage, in that order. URL beats sessionStorage beats localStorage.

`name()` is a simple function that converts from setting name (e.g.: `'level'`) to platform-specific name (e.g. 'LOG' for Node JS and 'log' for browsers):

```js
// convert option name to platform style
function name(n){
  return n == 'level' ? 'log' : n == 'debug' ? 'debug' : 'log_' + n
}
```

It is part of a much more advanced settings mechanism I am building for ulog v2. You will be able to configure log levels for individual loggers easily using any of these 3 mechanisms.

Thanks for your feedback here. It is enormously motivating to see people actually using the code I wrote :)

**Comment by Download** [comment] 2019-09-08 10:59
> BTW, to keep ulog tiny, all 'extra' features could come into some sub-module.

Yeah, I've been thinking about this.

Particularly, I am adding some much more advanced formatting and output options. But it takes up valuable space...

I was thinking, maybe I can load the code for the formatters only when you have set the setting to some non-empty value. In pseudo-code:

```js
if (ulog.get('format')) {
  ulog.load('formats.js')
  // do formatting stuff here
}
```

The problem is I end up building a script loader if I am not careful. I need a simple yet powerful way to load scripts on the fly. Also it is a bit problematic that script loading is async, whereas all other ulog functions are sync currently... Probably I will release a version of ulog that is simply a bigger bundle first and only when everything is working fine will I look into making the loading dynamic.

Do appreciate your input! Keep it coming 👍

**Comment by johnd0e** [comment] 2019-09-08 13:04
May be better keep things simpler, and leave loading part completely on user code.
He can load extra formatter in the same way as he loads `ulog` itself.

**Comment by youk** [comment] 2020-06-06 00:15
Why won't you remove from the readme the below section which is obviously not working for 2.0?

> Script tag
> 
> If you want, you can import ulog with a script tag:
> 
> <script src="https://cdn.rawgit.com/download/ulog/2.0.0-beta.7/ulog.min.js"></script>
> <script src="myscript.js"></script>

**Comment by Download** [comment] 2020-07-28 13:23
@youk 
Because that part of the README is actually auto-generated.
What I did wrong was publish a beta way to early... so users get confused. Sorry, my bad.
I am closing this issue. Everything that was said here has been taken into consideration for v2:

- Configure from URL will work (will be equivalent to using program arguments in Node JS)
- Configure from localStorage will work (will be equivalent to using env vars in Node JS)
- Script include will work without errors
- Will support 'mods' to add functionality by requiring a small module and adding it to ulog
- Will not support lazy loading for the time being, but this will remain a wish for me and will get implemented when I find a good way to do it

@youk @johnd0e 
Thank you guys for your support and feedback! Love you!

**Closed by Download** 2020-07-28 13:23 UTC

**Comment by youk** [comment] 2020-07-28 13:29
Thank you.
